export const BUILDINGS = {
  ALT: "Altschul Hall",
  AVH: "Avery Hall",
  BAR: "Barnard Hall",
  BUT: "Butler Library",
  BWY: "Broadway Residence Hall",
  DIA: "Diana Center",
  DOD: "Dodge Building",
  FLS: "Fairchild Life Sciences Building",
  HAM: "Hamilton Hall",
  IAB: "International Affairs Building",
  JRN: "Journalism Building",
  KNT: "Kent Hall",
  KNX: "Knox Hall",
  LEH: "Lehman Hall",
  LER: "Alfred Lerner Hall",
  LEW: "Lewisohn Hall",
  MAT: "Mathematics Building",
  MCY: "Macy Hall",
  MIL: "Milbank Hall, Barnard",
  MLC: "Milstein Center, Barnard",
  MUD: "Seeley W. Mudd Building",
  NWC: "Northwest Corner",
  PHI: "Philosophy Hall",
  PRN: "Prentis Hall",
  PUP: "Pupin Laboratories",
  SCEP: "Schapiro Center",
  SCH: "Schermerhorn Hall",
  SCHP: "Schapiro Residence Hall",
  URI: "Uris Hall",
  UTS: "Union Theological Seminary",
};

export const STATUSES = ["SUBMITTED", "PROCESSING", "RESOLVED"];
